services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    volumes:
      - ./packages/backend:/app/packages/backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@db:5432/prisma

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app/packages/frontend

volumes:
  postgres:
