version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build: backend
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    build: frontend
    ports:
      - "3000:3000"

volumes:
  postgres:
